SRC	=\
	User/_handleINVITE.cpp	\
	User/_handleNICK.cpp	\
	User/_handlePASS.cpp	\
	User/_handleUSER.cpp	\
	User/_handlePRIVMSG.cpp	\
	User/_handleJOIN.cpp	\
	User/_handlePING.cpp	\
	User/_handleWHO.cpp		\
	User/_handlePART.cpp	\
	User/_handleTOPIC.cpp	\
	User/_handleMODE.cpp	\
	User/_handleLIST.cpp	\
	User/_handleISON.cpp	\
	User/User.cpp			\
\
	Channel.cpp			\
	ListenSocket.cpp	\
	main.cpp			\
	NumericReplies.cpp	\
	Server.cpp			\
	SignalHandler.cpp	\
	Command.cpp			\
	Topic.cpp			\
